name: beacon_scanner_platform_interface
description: A common platform interface for the beacon_scanner_platform_interface plugin.
version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0
  meta: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
